### ISSUE TITLE
Filters for tasks of managees: by due dates, priprity etc

### ISSUE THREAD

**Issue by aviriel** [ITDSystems/alvex-manager-dashboard-tasks#5]
Default filters for tasks of managees page (like it's on default My tasks page)

**Comment by douglascrp** [comment]
@aviriel It is me again.
I will need this functionality too, so, I would like to ask if you have any plan for this feature, or if I should try to implement it.
Do you have any idea on how to achieve this or any work already started that I can follow?
Again, I am just trying to avoid working on the same thing as you.

**Comment by aviriel** [comment]
Hi Douglas,

We don't have any plans to implement it in the nearest future, so you can take a look at it if you want. 
Now it works simply. We retrieve all managed users as array via: http://localhost:8080/share/proxy/alfresco/api/alvex/orgchart/user/admin/managees. And then render their tasks one by one.
You may implement new API like this (https://github.com/ITDSystems/alvex-orgchart/blob/d7ebb2fe086f426dddd5b9ff5aa93e5753e6e798/repo/src/main/amp/config/alfresco/extension/templates/webscripts/orgchart-managees/orgchart-managees.get.js) that returns you not one array, but several arrays by departments. And implement a filter for them. If you want to have more complex task then you can also replace a list of tasks with datagrid as it's done on My Tasks page :)

**Comment by aviriel** [comment]
Also be aware of https://github.com/ITDSystems/alvex-orgchart/issues/26 if you will use this component. We need to fix it, but still no time to do it :(

**Comment by douglascrp** [comment]
@aviriel I was re-reading this issue carefully, and now I see that what I am trying to implement is a different requirement, which is to be able to filter by due date, priority, and so on, just like the OOTB page.
I think I am going to create a new issue for this specific problem.
What do you think?

**Comment by douglascrp** [comment]
@aviriel What can we do with this issue?
As we were discussing, what I did is different from what is described here, and even more, I only made changes in the page, and not in the dashlet.
I believe it will be better to break this issue in small ones.

Let me know what you think.

**Comment by aviriel** [comment]
Created #16 for initial task :) Close this as fixed
